version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_${GROUP_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    # volumes
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Network
    networks:
      - app_networks

  # --- 2. APP SERVICE ---
  sistem-arsip:
    build: ./app
    container_name: sistem_arsip_${GROUP_NAME}
    restart: always
    expose:
      - "3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_PORT=3000
    depends_on:
      - db_service
    # Network
    networks:
      - app_networks

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_${GROUP_NAME}
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sistem-arsip
    # Network
    networks:
      - app_networks
    

#--- VOLUMES AND NETWORKS ---
# tambahkan bagian volumes dan networks di sini
volumes:
  db_data:
    name: mysql_data_${GROUP_NAME}
    driver: local

networks:
  app_networks:
    driver: bridge
    name: net_tekser_${GROUP_NAME}